VAE_INPUT_HEIGHT = 64
VAE_INPUT_WIDTH = 64
VAE_INPUT_DIM = (VAE_INPUT_HEIGHT, VAE_INPUT_WIDTH, 3)
VAE_Z_DIM = 32
VAE_DENSE_SIZE = 1024
VAE_BATCH_SIZE = 32

GRU_TIME_STEPS = 24
GRU_BATCH_SIZE = 32

NUMBER_MIXTURES = 10
